language: scala

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.sbt/1.0/dependency
    - $HOME/.sbt/boot/scala*
    - $HOME/.sbt/launchers
    - $HOME/.ivy2/cache
    - $HOME/.coursier

# Tricks to avoid unnecessary cache updates
before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - rm -rf $HOME/.ivy2/local

jdk:
  - oraclejdk8

# https://travis-ci.community/t/solved-oraclejdk8-installation-failing-still-again/3428
dist: trusty

script:
  ## This runs the template with the default parameters, and runs test within the templated app.
  - sbt -Dfile.encoding=UTF8 -J-XX:ReservedCodeCacheSize=256M test
